### ISSUE TITLE
Ignoring hidden files like ".svn"

### ISSUE THREAD

**Issue by n3storm** [lucuma/Clay#19]
I am trying to ignore .svn directories in latest Clay (settings.py version)

```
FILTER=['base.html','more_link.html','.*']
IGNORE = ['.*','*svn*',]
```

Not only this doesn't work but also something weird is happening as, when builiding, Clay is trying to move "svn" entries in source, as well as ".svn" entries.

```
  static/fonts/.svn/prop-base/glyphicons-halflings-regular.ttf.svn-base
  static/fonts/.svn/prop-base/glyphicons-halflings-regular.eot.svn-base
  static/fonts/.svn/prop-base/glyphicons-halflings-regular.woff.svn-base
  svn/entries
Traceback (most recent call last):
  File "/usr/local/bin/clay", line 9, in <module>
    load_entry_point('Clay==2.9.3', 'console_scripts', 'clay')()
  File "/usr/local/lib/python2.7/dist-packages/clay/manage.py", line 75, in main
    manager.run()
  File "/usr/local/lib/python2.7/dist-packages/baker.py", line 823, in run
    value = self.apply(*self.parse(argv), instance=instance)
  File "/usr/local/lib/python2.7/dist-packages/baker.py", line 801, in apply
    return cmd.fn(*newargs, **newkwargs)
  File "/usr/local/lib/python2.7/dist-packages/clay/manage.py", line 63, in build
    c.build(pattern)
  File "/usr/local/lib/python2.7/dist-packages/clay/main.py", line 299, in build
    self.build_page(path)
  File "/usr/local/lib/python2.7/dist-packages/clay/main.py", line 271, in build_page
    return copy_if_updated(sp, bp)
  File "/usr/local/lib/python2.7/dist-packages/clay/helpers.py", line 48, in copy_if_updated
    newt = os.path.getmtime(path_in)
  File "/usr/lib/python2.7/genericpath.py", line 54, in getmtime
    return os.stat(filename).st_mtime
OSError: [Errno 2] No such file or directory: '***/web/source/svn/entries'
```

I manually created ".svn" and ".git" files in my source root directory but this doesn't break the build.

**Comment by jpscaletti** [comment]
I'm sorry, there were many things that weren't working with this project. A clean rewrite is under way.
