### ISSUE TITLE
Doesn't build

### ISSUE THREAD

**Issue by aidan-fitz** [lucuma/Clay#22]
I'm running `clay build` on Ubuntu 16.04 and got this error message:

```
Traceback (most recent call last):
  File "/usr/local/bin/clay", line 9, in <module>
    load_entry_point('Clay==2.12.6', 'console_scripts', 'clay')()
  File "/usr/local/lib/python2.7/dist-packages/clay/manage.py", line 85, in main
    manager.run()
  File "/usr/local/lib/python2.7/dist-packages/baker.py", line 888, in run
    value = self.apply(*self.parse(argv), instance=instance)
  File "/usr/local/lib/python2.7/dist-packages/baker.py", line 866, in apply
    return cmd.fn(*newargs, **newkwargs)
  File "/usr/local/lib/python2.7/dist-packages/clay/manage.py", line 73, in build
    c.build(pattern)
  File "/usr/local/lib/python2.7/dist-packages/clay/main.py", line 315, in build
    self.build_page(path)
  File "/usr/local/lib/python2.7/dist-packages/clay/main.py", line 294, in build_page
    content = self.render(path, self.settings)
  File "/usr/local/lib/python2.7/dist-packages/clay/main.py", line 94, in render
    return self.app.render_template(path, context, host, port)
  File "/usr/local/lib/python2.7/dist-packages/clay/wsgiapp.py", line 68, in render_template
    self.thumbnailer.storage.base_url = '/'
AttributeError: 'Thumbnailer' object has no attribute 'storage'
```

However, it compiles successfully when I do `clay run`.

**Comment by etienned** [comment]
It's because the Moar dependency was updated recently with non-backwards compatible changes. You need to install a previous version of Moar (like 1.3.3).
