### ISSUE TITLE
Error running clay

### ISSUE THREAD

**Issue by EmmanuelPerezP** [lucuma/Clay#25]
Im getting this error when i try to run 

`clay new site
`

i tried googling but i found nothing :P

```
Traceback (most recent call last):
  File "/home/ema/.local/bin/clay", line 7, in <module>
    from clay.manage import main
  File "/home/ema/.local/lib/python2.7/site-packages/clay/__init__.py", line 10, in <module>
    from .main import Clay  # noqa
  File "/home/ema/.local/lib/python2.7/site-packages/clay/main.py", line 18, in <module>
    from .wsgiapp import WSGIApplication
  File "/home/ema/.local/lib/python2.7/site-packages/clay/wsgiapp.py", line 14, in <module>
    from .markdown_ext import MarkdownExtension
  File "/home/ema/.local/lib/python2.7/site-packages/clay/markdown_ext/__init__.py", line 1, in <module>
    from .jinja import MarkdownExtension  # noqa
  File "/home/ema/.local/lib/python2.7/site-packages/clay/markdown_ext/jinja.py", line 7, in <module>
    from .render import md_to_jinja
  File "/home/ema/.local/lib/python2.7/site-packages/clay/markdown_ext/render.py", line 31, in <module>
    lazy_ol=True
  File "/home/ema/.local/lib/python2.7/site-packages/markdown/core.py", line 100, in __init__
    configs=kwargs.get('extension_configs', {}))
  File "/home/ema/.local/lib/python2.7/site-packages/markdown/core.py", line 126, in registerExtensions
    ext = self.build_extension(ext, configs.get(ext, {}))
  File "/home/ema/.local/lib/python2.7/site-packages/markdown/core.py", line 166, in build_extension
    module = importlib.import_module(ext_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: Failed loading extension "smart_strong".
```

**Comment by TuxCoder** [comment]
you have to downgrade `markdown`
`pip install "markdown<3"`

or change the code so it runs with the new version 3 of markdown

also you need python2
